package com.john.shopbot.item;

/**
 * Copyright CloudMine LLC
 * User: johnmccarthy
 * Date: 5/26/12, 5:56 PM
 */
public enum ArmorItemProperty {
    NONE, ALL_RESISTANCE, ARCANE_POWER_CRIT, ARCANE_RESISTANCE, ARMOR, ATTACK_SPEED,
    BARBARIAN_BASH, BARBARIAN_CLEAVE, BARBARIAN_FRENZY, BARBARIAN_REND, BARBARIAN_REVENGE, BARBARIAN_WEAPON_THROW,
    CHANCE_CHILL, CHANCE_FEAR, CHANCE_FREEZE, CHANCE_IMMOBOLIZE, CHANCE_KNOCKBACK, CHANCE_SLOW, CHANCE_STUN,
    COLD_RESISTANCE, CRITICAL_HIT_CHANCE, CRITICAL_HIT_DAMAGE, CROWD_CONTROL_REDUCTION,
    DEMON_H_CHAKRAM, DEMON_H_EVASIVE, DEMON_H_GRANDES, DEMON_H_IMPALE, DEMON_H_SPIKE,
    DEXTERITY, EXPERIENCE, EXTRA_HEALTH_FROM_GLOBES, FIRE_RESISTANCE, GOLD_FIND, HAS_SOCKETS, HATRED_REGENERATION, INDESTRUCTABLE,
    INTELLIGENCE, LIFE_PERCENT, LIFE_REGENERATION, LIFE_STEAL, LIFE_PER_SPIRIT, LIGHTNING_RESISTANCE, MAGIC_FIND, MANA_REGENERATION,
    MAX_ARCANE_POWER, MAX_DISCIPLINE, MAX_FURY, MAX_MANA,
    MONK_CRIPPLING, MONK_CYCLONE, MONK_DEADLY_REACH, MONK_EXPLODING_PALM, MONK_FISTS_OF_THUNDER, MONK_SWEEPING_WIND, MONK_WAY_OF_THE_HUNDRED,
    MOVEMENT_SPEED, PHYSICAL_DAMAGE_TO_ATTACKER, PHYSICAL_RESISTANCE, PICKUP_RADIUS, POISON_RESISTANCE,
    REDUCED_DAMAGE_FROM_ELITES, REDUCED_DAMAGE_FROM_MELEE_ATTACKS, REDUCED_DAMAGE_FROM_RANGED_ATTACKS, REDUCED_LEVEL_REQUIREMENTS,
    SPIRIT_REGENERATION, STRENGTH, VITALITY,
    WITCH_D_ACID_CLOUD, WITCH_D_FIREBATS, WITCH_D_SUMMON_ZOMBIE,
    WIZARD_ARCANE_TORRENT, WIZARD_DISINTEGRATE, WIZARD_ELECTROCUTE, WIZARD_EXPLOSIVE_BLAST, WIZARD_HYDRA, WIZARD_RAY_OF_FROST;
}
